version: '3.9'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001"
    environment:
      - NODE_ENV=production

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server